default_platform(:ios)

platform :ios do
  desc "Build the app and send it to TestFlight / App Store Connect"
  lane :release_to_testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: false
    )

    build_app(
      scheme: "UsaBem",
      export_method: "app-store",
      skip_profile_detection: true,
      export_options: {
        method: "app-store",
        signingStyle: "manual"
      },
      xcargs: "CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=''"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end